# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minecraft:
  gamemode: 'survival'
  motd: 'First try at a k8s minecraft server' # Message of the Day
  port: 25565

volume:
  storage: 3Gi
  path: '/home/local-volumes/minecraft' # Path to wherever you want to save your worldfile

resources:
  requests:
    memory: 2Gi
    cpu: 500m

serviceAccount:
  create: true