# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ********REQUIRED********
node:
  hostname: 'dell3' # Your kube node's hostname
# ************************

minecraft:
  gamemode: 'survival'
  motd: 'Your super-cool, super-kube, minecraft server' # Message of the Day
  port: 25565

volume:
  storage: 3Gi
  path: '/mnt/local-volumes/minecraft' # Path to wherever you want to save your worldfile

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1.5Gi

serviceAccount:
  create: true